name: Push Build to Artifactory
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      # This action checks out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      # This action sets up the JFrog CLI with the Artifactory URL and access token     
      - name: Install and config JF CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      # This command adds a new server configuration to the JFrog CLI   
      - run: |
          export SERVER_ID="test"
          jf c add $SERVER_ID --url=$URL --access-token=$ACCESS_TOKEN --interactive=false

      - run: |
          jf rt ping

          sudo apt-get install gcc g++ cmake  
              
          conan profile detect --force
          conan install . --output-folder=build --build=missing
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build .

          conan remote add conan-local ${{ secrets.ARTIFACTORY_URL }}/artifactory/api/conan/conan-dev-local
          conan remote login conan-dev-local sam -p ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          
          conan list --graph=create.json --graph-binaries=build --format=json > pkglist.json
          conan upload --list=pkglist.json -r=conan-dev-local -c

          
          #jf npmc --repo-deploy=lego-npm-virt --repo-resolve=lego-npm-remote
          #jf npm install --build-name=lego-npm-build --build-number=1.0.${{github.run_number}}
          #jf rt build-add-git lego-npm-build 1.0.${{github.run_number}}
          #jf rt build-collect-env lego-npm-build 1.0.${{github.run_number}}
          #jf rt npm-publish --build-name=lego-npm-build --build-number=1.0.${{github.run_number}}
          #jf rt build-publish lego-npm-build 1.0.${{github.run_number}}
          #jf rt build-scan lego-npm-build 1.0.${{github.run_number}}
          #jf rt build-promote lego-npm-build 1.0.${{github.run_number}} lego-npm-prod-local --status=production

